import React, { useState } from "react";
import Head from "next/head";
import { useRouter } from "next/router";
import { Button, Layout } from "antd";
import ConnectWallet from "@/components/ConnectWallet";
import styles from "./index.module.css";
import { Sidebar } from "@/components/Sidebar";
import { Content } from "antd/es/layout/layout";
import { useNavigationStore } from "@/states/navState.state";
import Mints from "@/components/Mints";
import Messages from "@/components/Messages";

export default function Dashboard() {
  const navState = useNavigationStore((state: any) => state.navState);

  const handleNavigation = (component: string) => {
    switch (component) {
      case "mints":
        return <Mints />;
      case "messages":
        return <Messages />;
      default:
        return <h1>Page not found!</h1>;
    }
  };

  return (
    <>
      <Head>
        <title>Dashboard- Kiwi</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.container}>
        <Sidebar />
        <div className={styles.navComponent}>{handleNavigation(navState)}</div>
        <ConnectWallet />
      </div>
    </>
  );
}
