import React, { useEffect, useState } from "react";
import Head from "next/head";
import { useRouter } from "next/router";
import { Button, Layout } from "antd";
import ConnectWallet from "@/components/ConnectWallet";
import styles from "./index.module.css";
import { Sidebar } from "@/components/Sidebar";
import { Content } from "antd/es/layout/layout";
import { useNavigationStore } from "@/states/navState.state";
import Mints from "@/components/Mints";
import Messages from "@/components/Messages";
import Editor from "@/components/Editor";
import Profile from "@/components/Profile";
import { useAccount, useWalletClient } from "wagmi";
import { useWalletStore } from "@/states/walletState.state";
import Navbar from "@/components/Navbar";
import { getAssets } from "@/services/assets.service";
import { message } from "antd";
import Achievements from "@/components/Achievements";

export default function Dashboard() {
    const navState = useNavigationStore((state: any) => state.navState);

    const { data: walletClient } = useWalletClient();

    const setWalletAddress = useWalletStore(
        (state: any) => state.setWalletAddress
    );

    useEffect(() => {
        handleGetAddress();
    }, [walletClient]);

    const handleGetAddress = async () => {
        if (walletClient) {
            const [address] = await walletClient.getAddresses();
            setWalletAddress(address);
        }
    };

    const [assetPack, setAssetPack] = useState<any>(null);

    const handleGetAssetPack = async () => {
        try {
            const response = await getAssets();
            if (response.status === 200) {
                setAssetPack(response.data.data);
            } else {
                message.error("Something went wrong");
            }
        } catch (err) {
            console.log(err, "fetch asset pack error");
            message.error("Something went wrong");
        }
    };

    useEffect(() => {
        handleGetAssetPack();
    }, []);

    const handleNavigation = (component: string) => {
        switch (component) {
            case "mints":
                return <Mints />;
            case "messages":
                return <Messages />;
            case "profile":
                return <Profile />;
            case "mintAvatar":
                return <Editor assetPack={assetPack} />;
            case "updateAvatar":
                return (
                    <Editor
                        assetPack={assetPack}
                        buttonText="Update"
                        isUpdate={true}
                    />
                );
            case "achievements":
                return <Achievements />;
            default:
                return <h1>Page not found!</h1>;
        }
    };

    return (
        <>
            <Head>
                <title>Dashboard- Kiwi</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <meta
                    name="viewport"
                    content="width=device-width, initial-scale=1"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <div className={styles.container}>
                <Sidebar />
                <div className={styles.mainContainerVertical}>
                    <Navbar />
                    {handleNavigation(navState)}
                </div>
            </div>
        </>
    );
}
